name: PR Closed Initialization Check

on:
  pull_request:
    types: [closed]

jobs:
  init-check:
    name: Initialize System After PR Closure
    runs-on: ubuntu-latest
    
    steps:
      - name: Wait for 5 minutes
        run: |
          echo "Waiting for 5 minutes before initialization check..."
          echo "Start time: $(date)"
          sleep 300
          echo "Wait completed at: $(date)"
          echo "Starting initialization check."
      
      - name: Check initialization status
        env:
          INIT_URL: ${{ vars.INIT_URL }}
        run: |
          if [ -z "$INIT_URL" ]; then
            echo "错误: INIT_URL 环境变量未设置"
            echo "请在仓库设置中配置 INIT_URL 变量"
            exit 1
          fi
          
          echo "正在访问初始化URL..."
          
          # Make HTTP request and capture response with timeout
          response=$(curl -s -w "\n%{http_code}" --connect-timeout 30 --max-time 60 "$INIT_URL" 2>/dev/null)
          curl_exit_code=$?
          
          if [ $curl_exit_code -ne 0 ]; then
            echo "错误: 无法访问初始化URL (curl exit code: $curl_exit_code)"
            case $curl_exit_code in
              6) echo "详细错误: 无法解析主机名" ;;
              7) echo "详细错误: 无法连接到服务器" ;;
              28) echo "详细错误: 请求超时" ;;
              *) echo "详细错误: 网络或服务器错误" ;;
            esac
            exit 1
          fi
          
          # Split response and status code
          http_code=$(echo "$response" | tail -n1)
          content=$(echo "$response" | sed '$d')
          
          echo "HTTP状态码: $http_code"
          echo "响应内容: $content"
          
          # Check if response content is "初始化成功"
          if [ "$content" = "初始化成功" ]; then
            echo "✅ 初始化成功！系统已正常初始化。"
            echo "工作流执行完成时间: $(date)"
            exit 0
          else
            echo "❌ 初始化失败。"
            echo "预期响应: 初始化成功"
            echo "实际响应: $content"
            
            # Mask potential sensitive information in logs
            masked_content=$(echo "$content" | sed 's|https\?://[^[:space:]]*|[URL已屏蔽]|g' | sed 's/[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}\.[0-9]\{1,3\}/[IP已屏蔽]/g' | sed 's/[a-zA-Z0-9._%+-]*@[a-zA-Z0-9.-]*\.[a-zA-Z]\{2,\}/[邮箱已屏蔽]/g')
            
            echo "响应内容（已屏蔽隐私信息）: $masked_content"
            echo "工作流执行失败时间: $(date)"
            exit 1
          fi